# -*- coding: utf-8 -*-
# Generated by Django 1.11.26 on 2019-11-18 18:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('verify_student', '0012_ssoverificationconfig'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SSOVerificationConfig',
            new_name='SSOReverificationConfig',
        ),
    ]
